server:
  port: 5000

spring:
  application:
    name: validation-dna
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb+srv://validation-dna:validation-dna2021@sgm-cluster.yozck.mongodb.net/validation-dna?retryWrites=true&w=majority&ssl=true&sslmode=require
      database: validation-dna
  profiles:
    active: local

management:
  endpoints:
    web:
      base-path: /